Fix bug in Rubinius install - 'rake install' doesn't actually build rubinius, so you need to run a separate 'rake' first.

diff --git a/scripts/manage b/scripts/manage
--- a/scripts/manage
+++ b/scripts/manage
@@ -305,9 +305,19 @@ RubyWrapper
       fi
 
       if [[ "$rvm_trace_flag" -eq 1 ]] ; then
-        rvm_ruby_make="$rvm_bin_path/rvm 1.8.7 rake install --trace" ; message="Compiling rbx"
+        rvm_ruby_make="$rvm_bin_path/rvm 1.8.7 rake --trace" ; message="Compiling rbx"
       else
-        rvm_ruby_make="$rvm_bin_path/rvm 1.8.7 rake install" ; message="Compiling rbx"
+        rvm_ruby_make="$rvm_bin_path/rvm 1.8.7 rake" ; message="Compiling rbx"
+      fi
+      __rvm_run "rake" "$rvm_ruby_make" "$message"
+      result=$? ; if [[ "$result" -gt 0 ]] ; then
+        $rvm_scripts_path/log "error" "There has been an error while running '$rvm_ruby_configure'. Aborting the installation." ; __rvm_pushpop ; return $result
+      fi
+
+      if [[ "$rvm_trace_flag" -eq 1 ]] ; then
+        rvm_ruby_make="$rvm_bin_path/rvm 1.8.7 rake install --trace" ; message="Installing rbx"
+      else
+        rvm_ruby_make="$rvm_bin_path/rvm 1.8.7 rake install" ; message="Installing rbx"
       fi
       __rvm_run "rake" "$rvm_ruby_make" "$message"
       result=$? ; if [[ "$result" -gt 0 ]] ; then
